site_name: ZScript Documentation
nav:
 - Intro: index.md
 - Syntax: syntax.md
 - Global Functions: global.md
 - Game Functions: game.md
 - Screen Functions: screen.md
 - FFC Functions: ffc.md
 - Link Functions: link.md
 - Misc: misc.md
theme: readthedocs
use_directory_urls: false
markdown_extensions:
    - admonition
    - def_list
    - codehilite
    - toc:
        permalink: "#"
extra:
    version: 2.53.2